name: ArgoCD_Pipeline
on:
  push: 
    branches:
      - main

jobs:
   
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo "New Version: $NEW_VERSION"
          docker build --build-arg VERSION_NUMBER=${{ env.NEW_VERSION }} -t "romi293/weather_app:${NEW_VERSION}" .
          
      - name: Publish to DockerHub
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker tag "romi293/weather_app:${NEW_VERSION}" "romi293/weather_app:${NEW_VERSION}"
          docker push "romi293/weather_app:${NEW_VERSION}"
      

       
########################################################

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image from DockerHub
        run: 
          docker pull "romi293/weather_app:${NEW_VERSION}"

     

